### PR TITLE
Deprecate DioError in favor of DioException

### LINKED ISSUE #1789: DioError is named incorrectly
### Request Statement

This has bothered me since a while. 
By dart convention, `DioError` is named incorrectly, as it is not an `Error`, but an `Exception`.

The distinction is important, as `Exception` is meant to be caught but `Error` is not.
`Error` signals a mistake from the programmer, that is usually not recoverable, 
while `Exception` is simply a failure of an operation, that can be handled by the program.

As per:
https://api.flutter.dev/flutter/dart-core/Error-class.html
https://api.flutter.dev/flutter/dart-core/Exception-class.html

### Solution Brainstorm

I understand that renaming `DioError` to `DioException` would be a very large breaking change.
This change could be introduced gradually by adding a typedef:

```dart
@Deprecated('Use DioException instead')
typedef DioError = DioException;
```

It's also noteworthy that while `DioException` is more correct based on convention, it is a bit longer to write than `DioError`, though this will probably be eliviated by IDE autocompletion.

It would perhaps be useful to provide a codemod for this transition, as there probably will be many projects that use `DioError` in many places.

### PR DESCRIPTION
**Pull request by clragon**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

Fixes #1789.

#### Quick summary

`DioError` is named incorrectly, as it is of type `Exception` and not `Error`.
The fix for this is to rename `DioError` to `DioException` and provide a typdef alias for `DioError` that is marked deprecated.
The typedef offers a grace period for migration and makes this a non-breaking change that can be introduced as soon as possible to notify users of the deprecation.

This PR makes these changes. Its worth considering also offering extra help with migration to users, for example by providing a lint with an automatic fix that turns `DioError` into `DioException` and `DioErrorType` into `DioExceptionType`.

### CODE REVIEW

File: dio/lib/src/dio_error.dart [hunk 1]
```diff
@@ -1,200 +1,10 @@
...
-  String toString() {
-    String msg = 'DioError [${type.toPrettyDescription()}]: $message';
-    if (error != null) {
-      msg += '\nError: $error';
-    }
-    return msg;
-  }
-}
+/// Deprecated in favor of [DioException] and will be removed in future major versions.
+@Deprecated('Use DioException instead')
```
Comment (AlexV525) [inline dio/lib/src/dio_error.dart:9]:
```suggestion
@Deprecated('Use DioException instead. This will be removed in 6.0.0')
```

File: dio/lib/src/dio_error.dart [hunk 2]
```diff
@@ -1,200 +1,10 @@
...
-        return 'request cancelled';
-      case DioErrorType.connectionError:
-        return 'connection error';
-      case DioErrorType.unknown:
-        return 'unknown';
-    }
-  }
-}
+/// Deprecated in favor of [DioExceptionType] and will be removed in future major versions.
+@Deprecated('Use DioExceptionType instead')
```
Comment (AlexV525) [inline dio/lib/src/dio_error.dart:4]:
```suggestion
@Deprecated('Use DioExceptionType instead. This will be removed in 6.0.0')
```

File: dio/CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,7 @@
 ## 5.1.2
 
 - Allow `FormData` to send a null entry value as an empty string.
+- Deprecate `DioError` in favor of `DioException`.
```
Comment (AlexV525) [inline dio/CHANGELOG.md:10]: The entry is placed in the wrong place. It should be under the unreleased section.

**Comment by clragon** [comment]
The test fail right now because I intentionally did not update the plugins with this change yet.
Should I do that anyways?

**Comment by kuhnroyal** [comment]
This would go into 5.2.0? And all the plugins need to also bump constraints and a new minor version?

**Comment by clragon** [comment]
Right, this change would go into 5.2.0, as its non breaking and it will tell users as soon as possible that `DioError` is deprecated.
I have updated the PR to include all plugins and their changelogs.

**Comment by clragon** [comment]
I assume that would happen with the release of the versions itself, and not with this PR.
But I can certainly include that.

**Comment by AlexV525** [comment]
> But then you also need to raise the constraint in the plugins to `dio: ^5.2.0`.

That should be unnecessary IMO. No codes have been deleted actually.

**Comment by AlexV525** [comment]
> But the plugins now use the new `DioException` which is being added in `5.2.0`.

Oh indeed. They should have new constraint then.

**Review by AlexV525 — CHANGES_REQUESTED** [review]

**Review by AlexV525 — APPROVED** [review]
