### PR TITLE
⚡️ Support relative `baseUrl` on the Web platform

### LINKED ISSUE #2087: Conditionally allows relative path for `baseUrl`
### Package

dio

### Version

5.4.0

### Operating-System

Web

### Output of `flutter doctor -v`

_No response_

### Dart Version

3.1.5

### Steps to Reproduce

Run the following snippet with `dart run`:
```dart
void main() {
  final dio = Dio(BaseOptions(baseUrl: 'api/'));
}
```

### Expected Result

A new Dio instance is created with the given `baseUrl` and can be used as usual.
It is a normal situation for web apps to separate their API under a separate endpoint group: `https://example.com/api/...`.

### Actual Result

The code above produces the following Assertion Error:
```
Unhandled exception:
'package:dio/src/options.dart': Failed assertion: line 145 pos 16: 'baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new BaseOptions (package:dio/src/options.dart:145:16)
#3      main (package:anthill_front/src/shared/utils/http_client.dart:8:19)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

Process finished with exit code 255
```

The exception can be avoided if one changes the `baseUrl` in the BaseOptions after it was created:
```dart
final dio = Dio(BaseOptions()..baseUrl = 'api/');
```
Which is quite strange and not expected solution.

### PR DESCRIPTION
**Pull request by AlexV525**
Resolves #2087.

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

File: dio/lib/src/options.dart [hunk 1]
```diff
@@ -141,9 +149,7 @@ class BaseOptions extends _RequestConfig with OptionsMixin {
     RequestEncoder? requestEncoder,
     ResponseDecoder? responseDecoder,
     ListFormat? listFormat,
-  })  : assert(connectTimeout == null || !connectTimeout.isNegative),
```
Comment (kuhnroyal) [inline dio/lib/src/options.dart:144]: Did you want to get remove the connect timeout assert without replacement?

Comment (AlexV525) [reply dio/lib/src/options.dart:144]: It's already covered by the setter: https://github.com/cfug/dio/blob/37ab8abd50e89180f7e2e9a9cf1c416cf854b924/dio/lib/src/options.dart#L114-L119

**Review by kuhnroyal — APPROVED** [review]
