### PR TITLE
[dio] Fix FormData encoding regression for maps with dynamic keys

### LINKED ISSUE #1741: FormData.fromMap is encoding request body automatically
### Package

dio

### Version

5.0.2

### Output of `flutter doctor -v`

_No response_

### Dart Version

2.19.2

### Steps to Reproduce

```
Future<FormData> mapToFormData(
  Map<String, dynamic> formData,
) async {
  try {
    return FormData.fromMap(formData);
  } catch (e) {
    rethrow;
  }
}
```

### Expected Result

The above code should return request body as:

- item[0][product_size_id]: 14

### Actual Result

Instead of the expected result the code is returning request body as:

- items%5B0%5D%5Bproduct_size_id%5D: 14

### LINKED ISSUE #1758: The result that FormData.fromMap builded on 5.0.3 is different from 3.0.6.
### Package

dio

### Version

5.0.3

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.6 on channel stable at /Users/jiayou/fvm/versions/3.3.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (5 months ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

There is a different result which from FormData.fromMap() between Dio(5.0.3) and Dio(3.0.9).  The result I expected is "spec[]" : "6", but it was "spec": "6" on 5.0.3.
1. Is there any setting that I can get the the result that the same as in 3.0.9? 
2. I have noticed that ListFormat.multiCompatible example is the result style I want. But I had put it in the options and nothing new happened.
```

### Dart Version

2.18.2

### Steps to Reproduce

```dart
Future<void> main(List<String> arguments) async {

  final data = {
    'key1': 'value1',
    'spec': [6],
  };

  Dio dio = Dio();

  await dio.post<Map<String, dynamic>>(
    'https://postman-echo.com/post',
    data: data,
    options: Options(
      contentType: Headers.formUrlEncodedContentType,
      method: 'post',
    )
  ).then((onValue) {
    print('===<Response>---\n$onValue');
  });
  
}
```
Run and see the result.

### Expected Result

```
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "key1": "value1",
        "spec[]": "6"
    },
    "headers": {
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "host": "postman-echo.com",
        "x-amzn-trace-id": "Root=1-641d62d2-581890fc6c16023f47191f33",
        "content-length": "24",
        "user-agent": "Dart/2.18 (dart:io)",
        "content-type": "application/x-www-form-urlencoded",
        "accept-encoding": "gzip"
    },
    "json": {
        "key1": "value1",
        "spec[]": "6"
    },
    "url": "https://postman-echo.com/post"
}
```

### Actual Result
```
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "key1": "value1",
        "spec": "6"
    },
    "headers": {
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "host": "postman-echo.com",
        "x-amzn-trace-id": "Root=1-641d62e6-6d4eb8246a594a63138a64be",
        "content-length": "18",
        "user-agent": "Dart/2.18 (dart:io)",
        "content-type": "application/x-www-form-urlencoded",
        "accept-encoding": "gzip"
    },
    "json": {
        "key1": "value1",
        "spec": "6"
    },
    "url": "https://postman-echo.com/post"
}
```

The  spec key/value should be "spec[]" : "6", not  "spec": "6"

### PR DESCRIPTION
**Pull request by kuhnroyal**
In relation to #1741 

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

Fixes #1741 
Fixes #1758

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@AlexV525 Please take a look, we should release this asap.

File: dio/test/utils.dart [hunk 1]
```diff
@@ -14,6 +14,8 @@ Encoding requiredEncodingForCharset(String charset) =>
 /// The URL for the current server instance.
 Uri get serverUrl => Uri.parse('http://localhost:${_server?.port}');
 
+final isWeb = identical(1, 1.0);
```
Comment (AlexV525) [inline dio/test/utils.dart:17]: Using this might be more accurate. https://github.com/cfug/dio/blob/c2347f3bf74250d83307798ae77f0eb04febe38f/plugins/cookie_manager/lib/src/cookie_mgr.dart#L7-L9

Comment (AlexV525) [inline dio/test/utils.dart:17]:
```suggestion
const isWeb = bool.hasEnvironment('dart.library.js_util')
    ? bool.fromEnvironment('dart.library.js_util')
    : identical(0, 0.0);
```

**Review by AlexV525 — APPROVED** [review]
