### PR TITLE
Fix set-cookie parsing

### LINKED ISSUE #1674: If multiply cookies present in set-cookie header, only first is saved.
### Package

cookie_manager

### Version

2.1.0

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64, locale en-UA)
    • Flutter version 3.7.3 on channel stable at /Users/vovchara/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (10 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/vovchara/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Dart Version

2.19.2

### Steps to Reproduce

1. create interceptor with cookiejar
client.interceptors.add(CookieManager(PersistCookieJar()));
2. make request to the endpoint the returns multiply cookies in single(!) `set-cookie` header.
3. only first cookie from `set-cookie` header is saved.

### Expected Result

CookieManager must iterate over all cookies in `set-cookie` header.

### Actual Result

Logged response header:
```
set-cookie: state_cookie=; expires=Sun, 19 Feb 2023 00:42:14 GMT; path=/; HttpOnly; secure; SameSite=Lax, token=some_long_string; expires=Sun, 19 Feb 2023 01:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax, refreshtoken=some_long_string; expires=Sat, 20 May 2023 00:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax
```
Actually saved in Storage:
```
{"/":{"state_cookie":"state_cookie=; Expires=Sat, 20 May 2023 00:43:15 GMT; Path=/; Secure; HttpOnly;_crt=1676767395"}}
```
This code just treat 1 value = 1 cookie which is wrong
https://github.com/cfug/dio/blob/62622e214a939c07402fdc0efda41fd5e89959ca/plugins/cookie_manager/lib/src/cookie_mgr.dart#L78

### PR DESCRIPTION
**Pull request by Vovcharaa**
### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [x] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [x] I have run the tests without failures

### Additional context and info (if any)

Fix #1674

### CODE REVIEW

**Comment by Vovcharaa** [comment]
RegEx taken here: https://github.com/dart-lang/http/issues/362#issuecomment-622106682

File: plugins/cookie_manager/lib/src/cookie_mgr.dart [hunk 1]
```diff
@@ -8,6 +8,8 @@ const _kIsWeb = bool.hasEnvironment('dart.library.js_util')
     ? bool.fromEnvironment('dart.library.js_util')
     : identical(0, 0.0);
 
+final setCookieReg = RegExp('(?<=)(,)(?=[^;]+?=)');
```
Comment (AlexV525) [inline plugins/cookie_manager/lib/src/cookie_mgr.dart:11]: This can be private.

**Review by AlexV525 — COMMENTED** [review]
Please add tests.

**Comment by Vovcharaa** [comment]
> Please add tests.

I have no experience with dart tests, so I am not sure if I can do this, but I will look into it.

**Comment by AlexV525** [comment]
> I have no experience with dart tests, so I am not sure if I can do this, but I will look into it.

This can be simply by expecting a multi-value cookie to be parsed as multi values. An example:

https://github.com/cfug/dio/blob/62622e214a939c07402fdc0efda41fd5e89959ca/dio/test/basic_test.dart#L12-L20

**Comment by Vovcharaa** [comment]
@AlexV525 done

File: plugins/cookie_manager/lib/src/cookie_mgr.dart [hunk 2]
```diff
@@ -8,6 +8,8 @@ const _kIsWeb = bool.hasEnvironment('dart.library.js_util')
     ? bool.fromEnvironment('dart.library.js_util')
     : identical(0, 0.0);
 
+final _setCookieReg = RegExp('(?<=)(,)(?=[^;]+?=)');
```
Comment (AlexV525) [inline plugins/cookie_manager/lib/src/cookie_mgr.dart:11]: Can you add more comments to help everyone understand how this regular expression works?

File: plugins/cookie_manager/test/cookies_test.dart [hunk 3]
```diff
@@ -49,6 +49,32 @@ void main() {
       HttpHeaders.cookieHeader: mockSecondRequestCookies,
     });
 
+    cookieManager.onRequest(options, mockRequestInterceptorHandler);
+  });
+  test('testing set-cookies parsing', () async {
+    const List<String> mockResponseCookies = [
+      "key=value; expires=Sun, 19 Feb 3000 00:42:14 GMT; path=/; HttpOnly; secure; SameSite=Lax",
+      "key1=value1; expires=Sun, 19 Feb 3000 01:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax, key2=value2; expires=Sat, 20 May 3000 00:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax",
```
Comment (AlexV525) [inline plugins/cookie_manager/test/cookies_test.dart:57]: I don't see any single quotes inside, so it should be wrapped with single quotes.

Comment (AlexV525) [inline plugins/cookie_manager/test/cookies_test.dart:57]:
```suggestion
      "key=value; expires=Sun, 19 Feb 3000 00:42:14 GMT; path=/; HttpOnly; secure; SameSite=Lax",
      "key1=value1; expires=Sun, 19 Feb 3000 01:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax, "
      "key2=value2; expires=Sat, 20 May 3000 00:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax",
```

File: plugins/cookie_manager/lib/src/cookie_mgr.dart (hunk 2 above)
Comment (Vovcharaa) [reply plugins/cookie_manager/lib/src/cookie_mgr.dart:20]: Comment generated by chatgpt because I am definitely worse in understanding regex than it.

File: plugins/cookie_manager/test/cookies_test.dart [hunk 4]
```diff
@@ -49,6 +49,33 @@ void main() {
       HttpHeaders.cookieHeader: mockSecondRequestCookies,
     });
 
+    cookieManager.onRequest(options, mockRequestInterceptorHandler);
+  });
+  test('testing set-cookies parsing', () async {
+    const List<String> mockResponseCookies = [
+      'key=value; expires=Sun, 19 Feb 3000 00:42:14 GMT; path=/; HttpOnly; secure; SameSite=Lax',
+      'key1=value1; expires=Sun, 19 Feb 3000 01:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax, '
+          'key2=value2; expires=Sat, 20 May 3000 00:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax',
```
Comment (talisk) [inline plugins/cookie_manager/test/cookies_test.dart:58]: Code format

File: plugins/cookie_manager/test/cookies_test.dart [hunk 5]
```diff
@@ -49,6 +49,33 @@ void main() {
       HttpHeaders.cookieHeader: mockSecondRequestCookies,
     });
 
+    cookieManager.onRequest(options, mockRequestInterceptorHandler);
+  });
+  test('testing set-cookies parsing', () async {
+    const List<String> mockResponseCookies = [
+      'key=value; expires=Sun, 19 Feb 3000 00:42:14 GMT; path=/; HttpOnly; secure; SameSite=Lax',
+      'key1=value1; expires=Sun, 19 Feb 3000 01:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax, '
```
Comment (talisk) [inline plugins/cookie_manager/test/cookies_test.dart:57]:
```suggestion
      'key1=value1; expires=Sun, 19 Feb 3000 01:43:15 GMT; path=/; HttpOnly; secure; SameSite=Lax',
```

Comment (talisk) [reply plugins/cookie_manager/test/cookies_test.dart:57]: Right?

Comment (AlexV525) [reply plugins/cookie_manager/test/cookies_test.dart:57]: Nope. This line is intended to test with multi-value parsing.

Comment (Vovcharaa) [reply plugins/cookie_manager/test/cookies_test.dart:57]: No, its a single string split for convenience and readability in 2 lines. So no commas as separator.

File: plugins/cookie_manager/test/cookies_test.dart (hunk 4 above)
Comment (Vovcharaa) [reply plugins/cookie_manager/test/cookies_test.dart:58]: This is how editor formated it

File: plugins/cookie_manager/test/cookies_test.dart (hunk 5 above)
Comment (talisk) [reply plugins/cookie_manager/test/cookies_test.dart:57]: > Nope. This line is intended to test with multi-value parsing.

OKay

**Review by AlexV525 — APPROVED** [review]

**Comment by AlexV525** [comment]
Sorry, please update the CHANGELOG too.

**Comment by Vovcharaa** [comment]
@AlexV525 done
