### PR TITLE
[native_dio_adapter] ✨ Adds `createCronetEngine` and `createCupertinoConfiguration`

### LINKED ISSUE #2039: [native_dio_adapter] Pre-defined `URLSessionConfiguration` will fail platforms other than Darwin
### Package

native_dio_adapter

### Version

1.1.1

### Operating-System

Android

### Output of `flutter doctor -v`

_No response_

### Dart Version

_No response_

### Steps to Reproduce

Run the below code on Android:
```dart
final dio = Dio();
dio.httpClientAdapter = NativeAdapter(
  cupertinoConfiguration:
      URLSessionConfiguration.ephemeralSessionConfiguration()
        ..allowsCellularAccess = false
        ..allowsConstrainedNetworkAccess = false
        ..allowsExpensiveNetworkAccess = false,
);
```

### Expected Result

No exceptions were thrown.

### Actual Result

```console
E/flutter (14736): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Platform android is not supported
E/flutter (14736): #0      linkedLibs.<anonymous closure> (package:cupertino_http/src/utils.dart:22:3)
E/flutter (14736): #1      linkedLibs (package:cupertino_http/src/utils.dart:24:2)
E/flutter (14736): #2      linkedLibs (package:cupertino_http/src/utils.dart)
E/flutter (14736): #3      new URLSessionConfiguration.ephemeralSessionConfiguration (package:cupertino_http/src/cupertino_api.dart:191:15)
E/flutter (14736): #4      _MyHomePageState._doGetRequest (package:example/main.dart:78:35)
```

### PR DESCRIPTION
**Pull request by AlexV525**
...to deprecate `cronetEngine` and `cupertinoConfiguration` for the `NativeAdapter`, to avoid platform exceptions.

Fixes #2039.

### New Pull Request Checklist

- [x] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [x] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [x] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [x] I have updated the documentation (if necessary)
- [x] I have run the tests without failures
- [x] I have updated the `CHANGELOG.md` in the corresponding package

### CODE REVIEW

**Review by ueman — APPROVED** [review]
Thanks, this is a really nice improvement in terms of usability!

File: plugins/native_dio_adapter/lib/src/native_adapter.dart [hunk 1]
```diff
@@ -17,14 +17,29 @@ import 'cupertino_adapter.dart';
...
+    )
     CronetEngine? androidCronetEngine,
+    @Deprecated(
+      'Use createCupertinoConfiguration instead. '
+      'This will cause platform exception on the Android platform. '
+      'This will be removed in v2.0.0',
+    )
     URLSessionConfiguration? cupertinoConfiguration,
   }) {
     if (Platform.isAndroid) {
```
Comment (ueman) [inline plugins/native_dio_adapter/lib/src/native_adapter.dart:35]: Unrelated to this PR, but I guess we could make use of https://pub.dev/packages/platform here later to enable better testing in the future
